In [2]:
import numpy as np

In [3]:
z1 = np.array([1,3,5,7,9])

In [4]:
z2 = z1 + 1

In [8]:
z1

array([1, 3, 5, 7, 9])

In [9]:
z2

array([ 2,  4,  6,  8, 10])

In [11]:
ind = [0,2,3]

In [12]:
z1[ind]

array([1, 5, 7])

In [13]:
ind = np.array([0,2,3])

In [14]:
z1[ind]

array([1, 5, 7])

In [15]:
z2

array([ 2,  4,  6,  8, 10])

In [16]:
z1

array([1, 3, 5, 7, 9])

In [17]:
z1 > 6

array([False, False, False,  True,  True], dtype=bool)

In [18]:
z1[z1>6]

array([7, 9])

In [22]:
z2[z1>6]

array([ 8, 10])

In [23]:
ind = z1 > 6

In [24]:
z1[ind]

array([7, 9])

In [25]:
z2[ind]

array([ 8, 10])

In [32]:
#slicing method

z1 = np.array([1,3,5,7,9])
w = z1[0:3]

In [33]:
w

array([1, 3, 5])

In [29]:
w[0] = 3

In [30]:
w

array([3, 3, 5])

In [31]:
z1

array([3, 3, 5, 7, 8])

In [36]:
# indexing method

z2 = np.array([1,3,5,7,9])
ind = [0,1,2]

In [37]:
z2

array([1, 3, 5, 7, 9])

In [38]:
ind

[0, 1, 2]

In [39]:
w2 = z2[ind]

In [40]:
w2[0]=3

In [41]:
w2

array([3, 3, 5])

In [42]:
z2

array([1, 3, 5, 7, 9])

In [47]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]

array([4, 5])

In [48]:
c = b[1:]
b[a] is c #indexing

False

In [49]:
b[a]

array([4, 5])

In [50]:
c

array([4, 5])