In [1]:
import numpy as np

In [11]:
# one dimensional arrays
x = np.array([1,2,3])
y = np.array([2,4,5])
# two dimensional arrays
X = np.array([[1,2,3], [4,5,6]])
Y = np.array([[2,4,6], [8,10,12]])

In [12]:
x

array([1, 2, 3])

In [13]:
y

array([2, 4, 5])

In [14]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
Y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
x[2]

3

In [17]:
x[0:2]

array([1, 2])

In [18]:
z = x + y

In [19]:
z

array([3, 6, 8])

In [20]:
X[:1,] #collumn

array([[1, 2, 3]])

In [21]:
Y[:1,] #collumn

array([[2, 4, 6]])

In [22]:
X[:1,] + Y[:1,]

array([[3, 6, 9]])

In [24]:
X[1,:]

array([4, 5, 6])

In [25]:
Y[1,:]

array([ 8, 10, 12])

In [28]:
X[1,:] + Y[1,:]

array([12, 15, 18])

In [29]:
X[1]

array([4, 5, 6])

In [30]:
Y[1]

array([ 8, 10, 12])

In [32]:
[2,4] + [6,8]

[2, 4, 6, 8]

In [33]:
np.array([2,4]) + np.array([6,8])

array([ 8, 12])

x = np.array([1,2,5])
x[1:2]

What does this return?

In [34]:
x = np.array([1,2,5])
x[1:2]

array([2])

Consider the following code:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

What does this return?

In [35]:
a = np.array([1,2])
b = np.array([3,4,5])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 