In [3]:
import numpy as np
import math

In [5]:
np.linspace(0, 100, 10)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [13]:
a = math.log10(10)
print(a)

1.0


In [16]:
b = math.log10(100)
print(b)

2.0


In [17]:
np.logspace(1,2,10)

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

In [18]:
np.logspace(np.log10(250), np.log10(500), 10)

array([ 250.        ,  270.01493472,  291.63225989,  314.98026247,
        340.19750004,  367.43362307,  396.85026299,  428.62199143,
        462.93735614,  500.        ])

In [19]:
X = np.array([[1,2,3],[4,5,6]])

In [20]:
X.shape #data attribute

(2, 3)

In [22]:
X.size #the elements of an array

6

In [29]:
x = np.random.random(10)

In [30]:
np.any(x > 0.9)

True

In [31]:
np.all(x >= 0.1)

True

In [32]:
x

array([ 0.27412751,  0.98952545,  0.64868969,  0.78608335,  0.83554549,
        0.4317071 ,  0.4946535 ,  0.39748042,  0.5343115 ,  0.31637105])

Consider the following code:

x=20
not np.any([x%i == 0 for i in range(2, x)])
What does the above code do?

In [35]:
x=20
not np.any([x%i == 0 for i in range(2, x)])

False

In [36]:
x=20
np.any([x%i == 0 for i in range(2, x)])

True

Finds whether x is prime. 