In [9]:
import numpy as np

In [10]:
zero_vector = np.zeros(5)

In [11]:
zero_matrix = np.zeros((5,3))

In [14]:
zero_vector

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
zero_matrix

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
x = np.array([1,2,3])

In [18]:
y = np.array([2,4,5])

In [20]:
x

array([1, 2, 3])

In [21]:
y

array([2, 4, 5])

In [22]:
a = np.array([[1,3],[5,9]])

In [23]:
a

array([[1, 3],
       [5, 9]])

In [24]:
A = a.transpose()

In [25]:
A

array([[1, 5],
       [3, 9]])

In [26]:
x = np.array([1,2,3])

In [28]:
x[0] = 11

In [29]:
x

array([11,  2,  3])